In [1]:
# Q.1 What is Numpy ?
#Numpy is python's open source library which deals with multi-dimensional arrays and matrices , random functions


In [2]:
# Q.2 Difference between List and arrays?
# List contains different type of data-type on the other hand arrays contains the values of same Data-type

In [5]:
# Q.3 How do you create a Numpy array with an python user-defined list?
import numpy as np
li = []
size = int(input("Enter the size of your array : "))
for i in range(size):
    v = int(input("Enter element "))
    li.append(v)
li
arr = np.array(li)
arr

Enter the size of your array : 5
Enter element 10
Enter element 20
Enter element 30
Enter element 40
Enter element 50


array([10, 20, 30, 40, 50])

In [11]:
# Q.4 How can you generate array filled with zeros and random values in the numpy
# Array with zeros
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [10]:
b = np.ones(5)
b

array([1., 1., 1., 1., 1.])

In [12]:
c = np.random.randint(1,20,15)
c

array([12,  6, 17,  3, 19, 12,  6,  2,  9,  4, 10, 19, 10, 13,  3])

In [17]:
# Q.4 What is the shape of numpy arrays?
a = np.array([[1,2,3,4],[5,6,7,8]])
a.shape # It give the output of the the row of column in the array

(2, 4)

In [69]:
# Q.5 How do we perform element wise add,subtraction,division,multiplication in numpy arrays
a = np.array([1,2,3,4]).reshape(2,2)
b = np.array([5,6,7,8]).reshape(2,2)
a


array([[1, 2],
       [3, 4]])

In [70]:
a+b

array([[ 6,  8],
       [10, 12]])

In [71]:
a-b

array([[-4, -4],
       [-4, -4]])

In [72]:
a*b

array([[ 5, 12],
       [21, 32]])

In [27]:
# Q.6 Explain the concept of slicing in the numpy arrays?
a = np.array([10,20,30,40,50,60])
b = a[1:4] #Slicing from the orginal array and the assigning it to b
b #but if we make change in the b it will also reflect back in the original array
b[:]=0
a
# To counter this we need to use copy function
# b = a[1:4].copy() It will make a copy of the values in the b and any changes in the b will not be reflected back in a

array([10,  0,  0,  0, 50, 60])

In [33]:
# Q.7 How can you reshape a array
# have to you use reshape() function
a = np.array([10,20,30,40,50,60])
a
a.reshape(3,2)


array([[10, 20],
       [30, 40],
       [50, 60]])

In [35]:
# Q.8 How can you Concatenate Two np arrays  horizontelly and vertically

a = np.array([[1,2,3,4],[5,6,7,8]])
b = np.array([[9,10,11,12],[13,14,15,16]])
np.hstack((a,b)) #Horizontly 

array([[ 1,  2,  3,  4,  9, 10, 11, 12],
       [ 5,  6,  7,  8, 13, 14, 15, 16]])

In [36]:
np.vstack((a,b)) #vertically 

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [5]:
# Q.9 How do you find min, max , mean , standard - deviation of an numpy array

a = np.array([10,20,30,40,50,60])
np.min(a)


10

In [6]:
np.max(a)

60

In [7]:
# mean 
np.mean(a)
# to learn

35.0

In [9]:
 # Standard Deviation
np.std(a)

17.07825127659933

In [6]:
# Q.10 What are universal function in numpy and why they are important?
# ufuncs stands for "Universal Functions" and they are NumPy functions that operate on the ndarray object.
# ufuncs are used to implement vectorization in NumPy which is way faster than iterating over elements.
# They also provide broadcasting and additional methods like reduce, accumulate etc. that are very helpful for computation.
# ufuncs also take additional arguments, like:

# where boolean array or condition defining where the operations should take place.

# dtype defining the return type of elements.

# out output array where the return value should be copied.
# vetcorization : Converting iterative statements into a vector based operation is called vectorization.

a = [10,20,30,40]
b = [50,60,70,80]
c = np.add(a,b)
print(c)




[ 60  80 100 120]


In [44]:
# Q.11 Explain how can you perform element wise comparision in boolean indexing in numpy arrays

a = np.arange(1,21)
a>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [45]:
a<10

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False, False, False, False, False, False,
       False, False])

In [46]:
a%2 == 0

array([False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True])

In [47]:
# Q.12 What are some practical use of numpy 
# To store the data in array on matrix format so we can easily perform multiple operation at once
# and it has many built in mathematical functions that can be used in data science and machine learning

In [48]:
# Q.13 How can you handle missing values in numpy arrays
# The missing data representation, NaN (acronym for Not a Number), is different; it is a special loating-point value recognized 
# by all systems that use the standard IEEE floating-point representation:

In [49]:
# Q.14 Differntiate between normal set and frozen set
# A frozenset is an unordered and unindexed collection of unique elements. It is immutable and it is hashable.
# It is also called an immutable set. Since the elements are fixed, unlike sets you can't add or remove elements from the set.
# Frozensets are hashable, you can use the elements as a dictionary key or as an element from another set. 
# frozensets are represented by the built-in function which is frozenset(). 
# It returns an empty set if there are no elements present in it. 

# A set is an unordered and unindexed collection of unique elements. 
# Sets are mutable, you can change the elements using a built-in function like add(), remove(), etc. 
# Since the elements are mutable and not in order, they don’t have hash values. 
# So you can’t access the elements with the help of index numbers.



In [50]:
# Q.15 Differntiate between Python2 and Python3

# 1. In Python 2 there is not necessary to put parenthesis in print but in python 3 it copulsory to use

# 2. Python 2 uses ASCII code but python 3 uses Unicode

#3. Python 3 have range function but python 2 doesn't have range function

In [52]:
# Q.16 What are Primitive Data-type in python
 
# Primitive Data type in python are int, string , float, bool.

In [85]:
# Q.17 Create a user defined loop who will reverse a user i/p
li = []
size =  int(input("Enter the size of ur input"))
for i in range(size):
    a = input("Enter : ")
    li.append(a)
ar = np.array(li)
i=size-1
while(i>=0):
    print(ar[i],end= "")
    i-=1

Enter the size of ur input5
Enter : 1
Enter : 2
Enter : 3
Enter : 4
Enter : 5
54321

In [20]:
li = []
arr = input("Enter your text")
size = len(arr)
st = arr[size::-1]
print(st)

Enter your texthello
olleh


In [1]:
# Q.18 What is the difference between strip and split in a string
# Strip => this method removes the character(s) passed by argument (or white spaces if no argument is passed)
# from the beginning and from the end of a string.
text = "Hello how are you"
text.split()
# Split => This method splits the input string into a list of strings. You can pass arguments too, known as delimiters. 
# If you don’t pass any parameter, it will split using the default delimiter - space

['Hello', 'how', 'are', 'you']

In [2]:
#  Q.19 Difference between isalnum(), isdigit() and find() in python string
# isalpha() => Give True if all characters in the string are alphanumeric and the string is not empty
# isdigit() => True if all characters in the string are digits and the string is not empty
# find() => method finds the first occurrence of the specified value
# The find() method returns -1 if the value is not found.
txt = "Hello it is nice to meet you"
val = txt.find("nice")
print(val)

12


In [3]:
# Q.20 What is the difference between list and tuple
# List =>
'''You can use Python lists to store data of multiple types simultaneously.
Lists help preserve data sequences and further process those sequences in other ways. 
Lists are dynamic.
Lists are mutable.
Lists are ordered.
An index is used to traverse a list.
'''
# Tuple =>
'''Tuples are used to store heterogeneous and homogeneous data.
Tuples are immutable in nature.
Tuples are ordered
An index is used to traverse a tuple.
Tuples are similar to lists. It also preserves the data sequence.
As tuples are immutable, they are faster than the list because they are static'''

'Tuples are used to store heterogeneous and homogeneous data.\nTuples are immutable in nature.\nTuples are ordered\nAn index is used to traverse a tuple.\nTuples are similar to lists. It also preserves the data sequence.\nAs tuples are immutable, they are faster than the list because they are static'

In [24]:
# Q.21 Create a list of tuple represents a student name and there corresponding score in 3 subject. 
# Write a function that take a list as input and return a new list containing only the students who have the average score
# greater than 80

student = [("Dhoni",70,50,90),("Virat",70,20,40),("Bumrah",60,10,10)]
def score():
    i=0
    a = []
    li = []
    while(i>3):
        a[i] = student[i][1]+student[i][2]+student[i][3] 
        print(a[0])
        if(a[i]>80):
            li.append(a[i])
        i+=1    
    return li
ans = score()
print(ans)




[]
